const img = {
    img1: require('./images/xuat file2-12.png'),
    img2: require('./images/xuat file2-13.png'),
    img3: require('./images/xuat file2-14.png'),
    img4: require('./images/xuat file2-25-25.png'),
    img5: require('./images/xuat file2-25-25.png'),
    img6: require('./images/xuat file2-20.png'),
    img7: require('./images/xuat file2-21.png'),
    img8: require('./images/quanlythucong.png'),
    img9: require('./images/kiemsoat.png'),
    img10: require('./images/xuat file2-25-22.png'),
    img11: require('./images/xuat file2-23.png'),
    img12: require('./images/khongthoaman.png'),
    img13: require('./images/xuat file2-26.png'),
    img14: require('./images/xuat file2-27.png'),
    img15: require('./images/xuat file2-28.png'),
    img16: require('./images/xuat file2-29.png'),
    img17: require('./images/xuat file2-30.png'),
    img18: require('./images/xuat file2-31.png'),
    img19: require('./images/xuat file2-32.png'),
    img20: require('./images/logo-gsot-taisaophaila.png'),
    img21: require('./images/thietke.png'),
    img22: require('./images/xuat file2-33.png'),
    img23: require('./images/caitienlientuc.png'),
    img24: require('./images/xuat file2-34.png'),
    img25: require('./images/xuat file2-35.png'),
    img26: require('./images/thietke.png'),
    img26: require('./images/quanlythucong.png'),
}


export default img;